package:
  name: pybtex-docutils
  version: !!str 0.2.1

source:
  fn: pybtex-docutils-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pybtex-docutils/pybtex-docutils-0.2.1.tar.gz
  md5: 7ae4b00562bd8881f582edf95009cc62
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pybtex-docutils = pybtex-docutils:main
    #
    # Would create an entry point called pybtex-docutils that calls pybtex-docutils.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docutils >=0.8
    - pybtex >=0.16
    - six

  run:
    - python
    - docutils >=0.8
    - pybtex >=0.16
    - six

# test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mcmtroffaes/pybtex-docutils
  license:  MIT License
  summary: 'A docutils backend for pybtex.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
