package:
  name: sphinx_rtd_theme
  version: !!str 0.1.6

source:
  fn: sphinx_rtd_theme-0.1.6.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinx_rtd_theme/sphinx_rtd_theme-0.1.6.tar.gz
  md5: 8df56a300c8c69f17e1ffbee194b2a26

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.1

  run:
    - python
    - sphinx >=1.1

test:
  # Python imports
  imports:
    - sphinx_rtd_theme

about:
  home: https://github.com/snide/sphinx_rtd_theme/
  license: BSD License
  summary: 'ReadTheDocs.org theme for Sphinx, 2013 version.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
