package:
  name: dm3lib
  version: '1.1'
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy
    - scipy
    - pillow

test:
  # Python imports
  imports:
    - DM3lib

about:
  home: microscopies.med.univ-tours.fr/pydm3reader
  license: BSD
  summary: 'Python module for parsing GATAN DM3 (DigitalMicrograph) files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
