package:
  name: sphinxcontrib-napoleon
  version: !!str 0.3.3

source:
  fn: sphinxcontrib-napoleon-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-napoleon/sphinxcontrib-napoleon-0.3.3.tar.gz
  md5: c02adde0c4ea6d481627c72fa9694822
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-napoleon = sphinxcontrib-napoleon:main
    #
    # Would create an entry point called sphinxcontrib-napoleon that calls sphinxcontrib-napoleon.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=0.6,<1.3b
    - six >=1.7
    - pockets >=0.2.1

  run:
    - python
    - sphinx >=0.6,<1.3b
    - six >=1.7
    - pockets >=0.2.1

test:
  # Python imports
  imports:
    - sphinxcontrib
    - sphinxcontrib.napoleon
    - tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://sphinxcontrib-napoleon.readthedocs.org
  license:  BSD License
  summary: 'Sphinx "napoleon" extension.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
