package:
  name: oset
  version: !!str 0.1.3

source:
  fn: oset-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/o/oset/oset-0.1.3.tar.gz
  md5: f23e5a545d2c77df3916398d2d39a3ab
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oset = oset:main
    #
    # Would create an entry point called oset that calls oset.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - oset

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://gitorious.com/sleipnir/python-oset
  license:  Python Software Foundation License
  summary: 'Ordered Set.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
