package:
  name: pockets
  version: !!str 0.2.4

source:
  fn: pockets-0.2.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pockets/pockets-0.2.4.tar.gz
  md5: 92eff6116937edfed56a8ed44bb3b99b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pockets = pockets:main
    #
    # Would create an entry point called pockets that calls pockets.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.5.2

  run:
    - python
    - six >=1.5.2

test:
  # Python imports
  imports:
    - pockets
    - tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pockets.readthedocs.org
  license:  BSD License
  summary: 'A collection of helpful Python tools!'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
