package:
  name: sphinxcontrib-bibtex
  version: !!str 0.3.2

source:
  fn: sphinxcontrib-bibtex-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.3.2.tar.gz
  md5: 6de8d82ea407abf1aebeb202255125ac
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-bibtex = sphinxcontrib-bibtex:main
    #
    # Would create an entry point called sphinxcontrib-bibtex that calls sphinxcontrib-bibtex.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - latexcodec >=0.3.0
    - pybtex >=0.17
    - pybtex-docutils >=0.2.0
    - six >=1.4.1
    - sphinx >=1.0
    - oset >=0.1.3

  run:
    - python
    - latexcodec >=0.3.0
    - pybtex >=0.17
    - pybtex-docutils >=0.2.0
    - six >=1.4.1
    - sphinx >=1.0
    - oset >=0.1.3

test:
  # Python imports
  imports:
    - sphinxcontrib
    - sphinxcontrib.bibtex

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mcmtroffaes/sphinxcontrib-bibtex
  license:  BSD License
  summary: 'A Sphinx extension for BibTeX style citations.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
